### ISSUE TITLE
smooth target encoding

### ISSUE THREAD

**Issue by mlisovyi** [MaxHalford/xam#6]
Hi,

thanks a lot for this handy toolkit! May i make a minor observation? It would be useful to cast the transformed column types into `np.float32` explicitly [here](https://github.com/MaxHalford/xam/blob/21b9e7b81dfed919cde363251eb80f25c0e77862/xam/feature_extraction/smooth_target_encoding.py#L60), while sometimes for unclear to me reason the type remains `'category'`, while in other cases it is casted into a float

**Comment by MaxHalford** [comment]
Hey! Sorry for the delay. Can you provide an example?

**Comment by mlisovyi** [comment]
the example was based on a particular dataset. I can dig it out, but I did not manage to understand the origin of the issue (for some features it worked just fine), so I would not be able to construct an example from scratch

**Comment by MaxHalford** [comment]
I'll find the issue once you dig out the example.

**Comment by mlisovyi** [comment]
May i share an example as a kaggle kernel? The use case in which i faced it was using data from one of kaggle comps

**Comment by MaxHalford** [comment]
Of course, no problem. My email address is maxhalford25@gmail.com if that helps.

**Comment by mlisovyi** [comment]
ok, I made a very minimal example. It turned out that conversion does not happen even in the basic scenario following the example in the docs:

```python
import xam
import pandas as pd
X = pd.DataFrame({'x_0': ['a'] * 5 + ['b'] * 5, 'x_1': ['a'] * 9 + ['b'] * 1})
y = pd.Series([1, 1, 1, 1, 0, 1, 0, 0, 0, 0])
X['x_0'] = X['x_0'].astype('category')
encoder = xam.feature_extraction.SmoothTargetEncoder(columns=['x_0', 'x_1'], prior_weight=3, suffix='')
print(encoder.fit_transform(X, y).info())
```
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
x_0    10 non-null category
x_1    10 non-null float64
dtypes: category(1), float64(1)
memory usage: 266.0 bytes
```

**Comment by MaxHalford** [comment]
Okay I just pushed a fix. Simply converting to a float dtype worked.

**Comment by mlisovyi** [comment]
indeed, simple conversion works. Thanks for the quick fix

**Comment by MaxHalford** [comment]
Cheers for opening the issue! It helps a lot.
