### ISSUE TITLE
meaning of prior_weight

### ISSUE THREAD

**Issue by bhomass** [MaxHalford/xam#8]
there is a prior_weight param used in Bayesian Target Encoding and a reference to a page to Additive Smoothing. However, on that page, I don't see any reference to the prior weight parameter. Is there some kind of explanation what that parameter means?

**Comment by MaxHalford** [comment]
Hey. The `prior_weight` parameter in `BayesianTargetEncoder` corresponds to the `alpha` (α) parameter from the [Additive smoothing](https://www.wikiwand.com/en/Additive_smoothing) page from Wikipedia. It basically corresponds to how smoothing you want to apply when computing your Bayesian means. The larger alpha, the more the means will be close to the prior mean, the lower it is the more they will be close to the mean obtained from the data.

I hope I cleared it up for you.
