### ISSUE TITLE
Error while pip install xam

### ISSUE THREAD

**Issue by surbhikakar** [MaxHalford/xam#9]
It does install the package but when the import has to be done in the code, it reports an error saying that "ModuleNotFoundError: No module named 'repos'
After doing pip install repos, again the error shows up as:
ModuleNotFoundError: No module named 'fabric.api'

**Comment by MaxHalford** [comment]
Hello,

`xam` is not available on PyPI, which means that `pip install xam` will not work. You can however do this: `pip install git+https://github.com/MaxHalford/xam --upgrade`.

I hope this helps.

**Comment by surbhikakar** [comment]
Yes. Thanks.
